"""Add Car model

Revision ID: 244257fa49bf
Revises: 
Create Date: 2024-08-23 15:27:40.848805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '244257fa49bf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('brand', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('fuel_type', sa.String(length=50), nullable=False),
    sa.Column('transmission', sa.String(length=50), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_car_brand'), 'car', ['brand'], unique=False)
    op.create_index(op.f('ix_car_fuel_type'), 'car', ['fuel_type'], unique=False)
    op.create_index(op.f('ix_car_mileage'), 'car', ['mileage'], unique=False)
    op.create_index(op.f('ix_car_model'), 'car', ['model'], unique=False)
    op.create_index(op.f('ix_car_price'), 'car', ['price'], unique=False)
    op.create_index(op.f('ix_car_transmission'), 'car', ['transmission'], unique=False)
    op.create_index(op.f('ix_car_year'), 'car', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_car_year'), table_name='car')
    op.drop_index(op.f('ix_car_transmission'), table_name='car')
    op.drop_index(op.f('ix_car_price'), table_name='car')
    op.drop_index(op.f('ix_car_model'), table_name='car')
    op.drop_index(op.f('ix_car_mileage'), table_name='car')
    op.drop_index(op.f('ix_car_fuel_type'), table_name='car')
    op.drop_index(op.f('ix_car_brand'), table_name='car')
    op.drop_table('car')
    # ### end Alembic commands ###
